/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs `scripts/sync-shared.mjs` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

/**
 * Formatting helpers. Pure functions, no platform deps.
 *
 * Currency / litres / kobo conversions live here so receipt views
 * (Arrival, Delivered, Complete, server PDF) all format the same way.
 * Drift between client and server formatting was harmless but ugly —
 * "₦1,200" on one screen, "NGN 1200.00" on another.
 */

/**
 * Format a naira amount as a currency string. NGN-locale, no decimal
 * places (the app deals in whole-naira amounts at the UI level; sub-
 * naira precision is preserved server-side as kobo).
 *
 * `formatCurrency(1234)` → `"₦1,234"`
 * `formatCurrency(0)`    → `"₦0"`
 */
export function formatCurrency(naira: number): string {
  if (!Number.isFinite(naira)) return "₦0";
  const rounded = Math.round(naira);
  return `₦${rounded.toLocaleString("en-NG")}`;
}

/**
 * Convert kobo to naira (whole). Use when reading raw money fields
 * off the server.
 *
 * `koboToNaira(123456)` → `1235`
 * `koboToNaira(99)`     → `1`
 */
export function koboToNaira(kobo: number): number {
  return Math.round(kobo / 100);
}

/**
 * Format kobo directly as a currency string. Avoids two-step
 * (`formatCurrency(koboToNaira(x))`) at call sites.
 */
export function formatKobo(kobo: number): string {
  return formatCurrency(koboToNaira(kobo));
}

/**
 * Format a litres / kg quantity. `unit` is unit-aware so callers
 * don't have to branch.
 *
 * `formatQuantity(15, "L")` → `"15 L"`
 * `formatQuantity(12.5, "kg")` → `"12.5 kg"`
 */
export function formatQuantity(qty: number, unit: "L" | "kg"): string {
  // Strip trailing .0 for whole numbers; keep one decimal otherwise.
  const formatted =
    Math.abs(qty - Math.round(qty)) < 0.05
      ? String(Math.round(qty))
      : qty.toFixed(1);
  return `${formatted} ${unit}`;
}
