/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs `scripts/sync-shared.mjs` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

/**
 * Idempotency-Key generator.
 *
 * Produces an RFC 4122 v4 UUID suitable for the `Idempotency-Key`
 * header on state-changing endpoints. The server-side middleware
 * dedupes by (userId, key, route) so a retried request after a flaky
 * network never double-charges / double-debits / double-transitions.
 *
 * One key per *user intent.* The same key MUST be reused if the
 * client retries the same logical action — never roll a fresh key
 * for a retry, that defeats the point. Roll a new key only when the
 * user takes a NEW action (e.g. taps Pay again after dismissing an
 * error and changing the amount).
 */

function rng(): number {
  return Math.random();
}

export function newIdempotencyKey(): string {
  const hex = "0123456789abcdef";
  const out: string[] = [];
  for (let i = 0; i < 36; i++) {
    if (i === 8 || i === 13 || i === 18 || i === 23) {
      out.push("-");
    } else if (i === 14) {
      out.push("4");
    } else if (i === 19) {
      out.push(hex[(rng() * 4) | 8]);
    } else {
      out.push(hex[(rng() * 16) | 0]);
    }
  }
  return out.join("");
}
