/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs `scripts/sync-shared.mjs` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

/**
 * Barrel export for the shared module.
 *
 * Import from `@/_shared` (mobile) or `../_shared` (server) so callers
 * don't have to know which file the symbol lives in.
 */

export * from "./status";
export * from "./transitions";
export * from "./trackPhase";
export * from "./socketEvents";
export * from "./format";
export * from "./idempotency";
