/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs `scripts/sync-shared.mjs` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

/**
 * Socket event names + payload types.
 *
 * The contract between client and server. Every event the server
 * emits and every event the client emits has its name listed here as
 * a constant + its payload typed. Imported by both sides — drift is
 * a TypeScript error.
 *
 * Conventions:
 *   - Event names are namespaced by domain:
 *       order:*    — Order-document lifecycle events (status changes,
 *                    delivered, cancelled).
 *       rider:*    — Rider-side push (location, dispatch offer).
 *       delivery:* — Delivery-document state pushes.
 *       route:*    — Polyline / ETA push from server.
 *   - Phase 2 of the execution plan adds room-based fanout via
 *     `delivery:<id>` — these names stay the same; only the relay
 *     pattern changes.
 */

import type { OrderStatus } from "./status";

/* ──────────────────────── Event names ──────────────────────── */

export const SocketEvents = {
  /** Server → client: any field on the Order document changed. */
  OrderUpdate: "order:update",

  /** Client → server: rider's current GPS coords. */
  RiderLocation: "rider:location",

  /** Server → client: relayed rider GPS for the matched order. */
  RiderLocationRelay: "rider:location",

  /** Server → client: cumulative litres dispensed (legacy; deprecated by
   *  the customer-side 3s animation but kept for forward compat). */
  DispenseProgress: "dispense:progress",

  /** Server → client: full delivery doc state-change push (Phase 3+). */
  DeliveryUpdate: "delivery:update",

  /** Server → client: new polyline available for this order (Phase 3+). */
  RouteUpdate: "route:update",

  /** Server → client: customer's active-order set/cleared (Phase 3+). */
  ActiveOrderSet: "active-order:set",
  ActiveOrderClear: "active-order:clear",
} as const;

/* ──────────────────────── Payload types ──────────────────────── */

export interface OrderUpdatePayload {
  orderId: string;
  status?: OrderStatus | string;
  eta?: number;
  /** Server emits the rider profile once on assignment so the
   *  customer's RiderCard can render without a follow-up GET. */
  rider?: {
    firstName: string;
    lastName?: string;
    plate?: string;
    rating?: number;
    phone?: string;
    initials?: string;
    profileImage?: string;
  };
  riderId?: string;
  /** Set on customer-confirm-delivered. */
  deliveredAt?: string;
  /** Final amount actually charged. Liquid = totalPrice. LPG = min(estimate, weighed actual). */
  totalCharged?: number;
  /** Points awarded on delivery — for the Delivered banner. */
  pointsEarned?: number;
  /** LPG-Swap weigh-in capture. */
  weighIn?: { emptyKg: number; fullKg: number; netKg: number };
}

export interface RiderLocationPayload {
  lat: number;
  lng: number;
  /** Set when relayed by server so the customer can filter by rider id. */
  riderId?: string;
}

export interface DispenseProgressPayload {
  orderId?: string;
  litres: number;
}

export interface DeliveryUpdatePayload {
  deliveryId: string;
  orderId: string;
  status: string;
  /** Convenience field — set on transitions that adjust the rider's
   *  earnings (delivered / dropped). */
  riderEarnings?: number;
}

export interface RouteUpdatePayload {
  orderId: string;
  /** Encoded polyline as [lat, lng] tuples. */
  polyline: [number, number][];
  /** Distance + ETA computed by the routing provider. */
  distanceM: number;
  durationS: number;
  /** Whether this polyline points to the station or the destination. */
  target: "station" | "destination";
}

export interface ActiveOrderSetPayload {
  orderId: string;
  status: string;
  product?: "liquid" | "lpg";
}

/* ──────────────────────── Room names ──────────────────────── */

/**
 * Room naming helpers. Used by both client and server to ensure
 * sockets join the same room name.
 *
 * Per-user rooms exist today (`user:<id>`). Per-delivery rooms are
 * introduced in Phase 2 of the execution plan (`delivery:<id>`).
 */
export const Rooms = {
  user: (userId: string) => `user:${userId}`,
  delivery: (deliveryId: string) => `delivery:${deliveryId}`,
} as const;
