/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs `scripts/sync-shared.mjs` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

/**
 * Single source of truth for order + delivery status enums.
 *
 * Drift between this file's union and any whitelist (e.g. the
 * `useActiveOrder` polling query, the `/api/rider/active` endpoint,
 * the `rider:location` socket relay) caused the "rider pin not
 * showing" + "customer sees X, rider sees Y" bug class. By centralizing
 * here, downstream code imports the same set everywhere — TypeScript
 * catches missed states at compile time.
 */

/* ──────────────────────── Order.status ──────────────────────── */

/**
 * Server-canonical Order status. Mirrors `server/src/models/Order.ts`.
 *
 * Two sub-pipelines coexist:
 *   - Legacy:   confirmed → assigned → in-transit → awaiting_confirmation → delivered
 *   - Granular: confirmed → assigned → at_plant → refilling → returning →
 *               arrived → dispensing → awaiting_confirmation → delivered
 *
 * The granular states are emitted by the upgraded rider app; the
 * customer-facing UI folds both pipelines into the same five
 * `TrackPhase` keys (see `trackPhase.ts`).
 */
export type OrderStatus =
  // Pre-payment / pre-confirm
  | "draft"
  | "pending_payment"
  | "pending"
  | "confirmed"
  // Dispatch
  | "assigning"
  | "assigned"
  // Legacy in-flight
  | "picked_up"
  | "in-transit"
  | "in_transit"
  // Granular v3 in-flight
  | "at_plant"
  | "refilling"
  | "returning"
  | "arrived"
  | "dispensing"
  // Hand-off + terminal
  | "awaiting_confirmation"
  | "delivered"
  | "rated"
  | "closed"
  // Failure / cancellation
  | "failed_payment"
  | "cancelled"
  | "cancelled_by_customer"
  | "cancelled_by_vendor"
  | "cancelled_by_rider";

/* ──────────────────────── Delivery.status ──────────────────────── */

/**
 * Server-canonical Delivery status. Mirrors
 * `server/src/models/Delivery.ts`.
 *
 * Distinct from OrderStatus but tightly coupled — when a rider tappes
 * "Mark at station", BOTH Order.status and Delivery.status flip to
 * `at_plant`. We currently maintain both in lockstep (see Phase 5 in
 * the execution plan for the eventual collapse to a single status).
 */
export type DeliveryStatus =
  | "pending"
  | "accepted"
  | "picked_up"
  | "at_plant"
  | "refilling"
  | "returning"
  | "arrived"
  | "dispensing"
  | "awaiting_confirmation"
  | "delivered"
  | "dropped"
  | "failed";

/* ──────────────────────── Active-status sets ──────────────────────── */

/**
 * Order statuses where the customer "has an order in flight."
 *
 * Drives:
 *   - The customer's tab-bar pulsing dot on the Track tab.
 *   - The `useActiveOrder` polling query.
 *   - The Track screen's "do I render the empty state?" decision.
 *
 * Includes BOTH legacy and granular states so the same set works
 * regardless of which rider-app version produced the order.
 */
export const ACTIVE_ORDER_STATUSES: readonly OrderStatus[] = [
  "pending",
  "confirmed",
  "assigning",
  "assigned",
  "picked_up",
  "in-transit",
  "in_transit",
  "at_plant",
  "refilling",
  "returning",
  "arrived",
  "dispensing",
  "awaiting_confirmation",
] as const;

/**
 * Delivery statuses where the rider has a job in flight.
 *
 * Drives:
 *   - `/api/rider/active` lookup whitelist.
 *   - `rider:location` socket relay status filter.
 *   - "Can the rider drop this delivery?" check.
 *
 * Critically, this includes the v3 granular states. Without them, an
 * upgraded rider's location pings stop relaying the moment they tap
 * "Mark at station" (the F1 / I2 bug).
 */
export const ACTIVE_DELIVERY_STATUSES: readonly DeliveryStatus[] = [
  "pending",
  "accepted",
  "picked_up",
  "at_plant",
  "refilling",
  "returning",
  "arrived",
  "dispensing",
  "awaiting_confirmation",
] as const;

/**
 * Delivery statuses from which the rider can drop the order. Same
 * set as ACTIVE_DELIVERY_STATUSES minus `awaiting_confirmation` (the
 * customer is the only one who can move past that point) and
 * `pending` (drop only makes sense after accept).
 */
export const DROPPABLE_DELIVERY_STATUSES: readonly DeliveryStatus[] = [
  "accepted",
  "picked_up",
  "at_plant",
  "refilling",
  "returning",
  "arrived",
  "dispensing",
] as const;

/* ──────────────────────── Helpers ──────────────────────── */

/**
 * Type guard — narrows a string to OrderStatus. Useful when reading
 * status from a server response that's typed as `string`.
 */
export function isOrderStatus(s: unknown): s is OrderStatus {
  return (
    typeof s === "string" &&
    (
      [
        "draft",
        "pending_payment",
        "pending",
        "confirmed",
        "assigning",
        "assigned",
        "picked_up",
        "in-transit",
        "in_transit",
        "at_plant",
        "refilling",
        "returning",
        "arrived",
        "dispensing",
        "awaiting_confirmation",
        "delivered",
        "rated",
        "closed",
        "failed_payment",
        "cancelled",
        "cancelled_by_customer",
        "cancelled_by_vendor",
        "cancelled_by_rider",
      ] as const
    ).includes(s as OrderStatus)
  );
}

/** Boolean — does this status represent an active customer-side order? */
export function isActiveOrder(status: string): boolean {
  return (ACTIVE_ORDER_STATUSES as readonly string[]).includes(status);
}

/** Boolean — does this delivery status represent an in-flight rider job? */
export function isActiveDelivery(status: string): boolean {
  return (ACTIVE_DELIVERY_STATUSES as readonly string[]).includes(status);
}
