/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs `scripts/sync-shared.mjs` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

/**
 * Customer-side track phase — the 5 buckets every Track-adjacent
 * screen reads from to decide what body to render. Folds BOTH the
 * legacy enum (what an un-upgraded rider app emits) and the v3
 * granular enum into the same five customer-facing phases — so the
 * customer screen lands the right design without waiting for the
 * rider app to upgrade.
 *
 * Mapping rationale:
 *   - pre-assignment: order paid, no rider yet (`pending` |
 *     `pending_payment` | `confirmed` | `assigning`).
 *   - assigned: rider accepted, possibly heading to pickup
 *     (`assigned`).
 *   - at-pickup: rider at the station refilling. Granular v3 emits
 *     `at_plant` / `refilling`; legacy collapses these into
 *     `assigned` so the customer can't see them on un-upgraded
 *     rider apps. Once the rider upgrades, the body flips
 *     automatically.
 *   - in-transit: rider has the fuel and is heading to the customer
 *     (`in-transit` / `in_transit` / `picked_up` / `returning`).
 *   - almost-there: rider is at the customer's gate or seconds away.
 *     v3 emits `arrived` / `dispensing`; legacy collapses to
 *     `awaiting_confirmation`. We also derive almost-there
 *     client-side when in-transit ETA drops to ≤ 1 min so the
 *     "< 1 min" UI surfaces today even on legacy rider apps.
 *
 * Unknown statuses default to `pre-assignment` so a future server
 * value never crashes the screen.
 */
export type TrackPhase =
  | "pre-assignment"
  | "assigned"
  | "at-pickup"
  | "in-transit"
  | "almost-there";

export interface TrackPhaseInput {
  status: string;
  hasRider: boolean;
  /** ETA in minutes. Drives the almost-there client-side derivation. */
  etaMinutes?: number | null;
}

export function getTrackPhase(input: TrackPhaseInput): TrackPhase {
  const s = input.status;

  // No rider yet — sheet shows the matching skeleton regardless of
  // server status nuance. `assigning` covers the dispatch window;
  // `pending` / `pending_payment` / `confirmed` cover the pre-dispatch
  // window after payment lands.
  if (
    !input.hasRider ||
    s === "pending" ||
    s === "pending_payment" ||
    s === "confirmed" ||
    s === "assigning"
  ) {
    return "pre-assignment";
  }

  // v3 granular — rider at the station.
  if (s === "at_plant" || s === "refilling") return "at-pickup";

  // v3 granular — rider arriving / dispensing on the customer side.
  if (s === "arrived" || s === "dispensing") return "almost-there";

  // Legacy + v3 in-transit — rider has the fuel, heading to customer.
  if (
    s === "in-transit" ||
    s === "in_transit" ||
    s === "picked_up" ||
    s === "returning"
  ) {
    if (typeof input.etaMinutes === "number" && input.etaMinutes <= 1) {
      return "almost-there";
    }
    return "in-transit";
  }

  // Legacy `awaiting_confirmation` — rider has marked delivery; we
  // route the customer off Track to the Arrival/Handoff screen, but
  // if we're still on Track for a render or two, present as
  // almost-there so the layout doesn't flash back to in-transit.
  if (s === "awaiting_confirmation") return "almost-there";

  // Default: rider exists, status unknown → assigned.
  return "assigned";
}
