/**
 * ⚠️  AUTO-GENERATED FROM mobile/gaznger/_shared/  ⚠️
 *
 * Do NOT edit this file directly — your changes will be overwritten
 * the next time someone runs `scripts/sync-shared.mjs` from the
 * mobile repo. Edit the canonical copy in mobile/gaznger/_shared/
 * instead, then re-run the sync.
 */

/**
 * Status transition matrix — single source of truth.
 *
 * Defines which Order.status flips are legal, by role. Both the server
 * (when validating PATCH /:orderId/status) and the client (when
 * deciding which CTAs to render on the rider track screen) consume
 * this matrix. Keeping them aligned was the missing piece in earlier
 * "rider tapped X but server rejected" bugs.
 */

import type { OrderStatus } from "./status";

export type TransitionRole = "customer" | "vendor" | "rider" | "admin";

export interface Transition {
  from: OrderStatus | string;
  to: OrderStatus | string;
}

/**
 * Per-role allowed transitions.
 *
 * - `customer`: cancel before dispatch.
 * - `vendor`:   confirm or cancel a pending order.
 * - `rider`:    every step of the granular pipeline + the legacy
 *               picked_up shortcut. LPG-Swap shortcuts (at_plant →
 *               returning, arrived → awaiting_confirmation) are
 *               legal — swap orders skip refilling and dispensing.
 * - `admin`:    any transition (audited via AuditLog).
 *
 * NOTE: Customer-confirm-delivery uses its own dedicated route
 * (`/confirm-delivery`) and is intentionally NOT in this matrix so
 * customers can't accidentally use the generic PATCH endpoint to
 * flip `delivered`.
 */
export const STATUS_TRANSITIONS: Record<TransitionRole, Transition[]> = {
  customer: [
    { from: "pending", to: "cancelled" },
  ],
  vendor: [
    { from: "pending", to: "confirmed" },
    { from: "pending", to: "cancelled" },
  ],
  rider: [
    // Legacy ladder — kept as compat shim for non-upgraded rider apps.
    { from: "in-transit", to: "awaiting_confirmation" },
    { from: "in_transit", to: "awaiting_confirmation" },

    // ── v3 granular ladder ──
    { from: "assigned", to: "at_plant" },
    { from: "at_plant", to: "refilling" },
    { from: "at_plant", to: "returning" }, // LPG-Swap skips refilling
    { from: "refilling", to: "returning" },
    { from: "returning", to: "arrived" },
    { from: "arrived", to: "dispensing" },
    { from: "arrived", to: "awaiting_confirmation" }, // LPG-Swap skips dispensing
    { from: "dispensing", to: "awaiting_confirmation" },
  ],
  admin: [],
};

/**
 * Boolean — is this transition legal for this role? Admin role
 * short-circuits to true (audited separately). Anyone else must have
 * the exact (from, to) pair listed.
 */
export function isAllowedTransition(
  role: TransitionRole,
  from: string,
  to: string
): boolean {
  if (role === "admin") return true;
  return STATUS_TRANSITIONS[role].some((t) => t.from === from && t.to === to);
}

/**
 * Returns every status reachable from `from` for the given role.
 * Useful for rider-side CTA rendering ("which next-step button do I
 * show given the current status?").
 */
export function nextStatusesFor(
  role: TransitionRole,
  from: string
): string[] {
  if (role === "admin") return [];
  return STATUS_TRANSITIONS[role]
    .filter((t) => t.from === from)
    .map((t) => t.to);
}
